# TMDB supported languages
SUPPORTED_LANGUAGES = [
    {"code": "af-ZA", "name": "Afrikaans", "flag": "🇿🇦"},
    {"code": "ar-AE", "name": "العربية (AE)", "flag": "🇦🇪"},
    {"code": "ar-BH", "name": "العربية (BH)", "flag": "🇧🇭"},
    {"code": "ar-EG", "name": "العربية (EG)", "flag": "🇪🇬"},
    {"code": "ar-IQ", "name": "العربية (IQ)", "flag": "🇮🇶"},
    {"code": "ar-JO", "name": "العربية (JO)", "flag": "🇯🇴"},
    {"code": "ar-LY", "name": "العربية (LY)", "flag": "🇱🇾"},
    {"code": "ar-MA", "name": "العربية (MA)", "flag": "🇲🇦"},
    {"code": "ar-QA", "name": "العربية (QA)", "flag": "🇶🇦"},
    {"code": "ar-SA", "name": "العربية (SA)", "flag": "🇸🇦"},
    {"code": "ar-TD", "name": "العربية (TD)", "flag": "🇹🇩"},
    {"code": "ar-YE", "name": "العربية (YE)", "flag": "🇾🇪"},
    {"code": "be-BY", "name": "Беларуская", "flag": "🇧🇾"},
    {"code": "bg-BG", "name": "Български", "flag": "🇧🇬"},
    {"code": "bn-BD", "name": "বাংলা", "flag": "🇧🇩"},
    {"code": "br-FR", "name": "Brezhoneg", "flag": "🇫🇷"},
    {"code": "ca-AD", "name": "Català (AD)", "flag": "🇦🇩"},
    {"code": "ca-ES", "name": "Català (ES)", "flag": "🇪🇸"},
    {"code": "ch-GU", "name": "Chamorro", "flag": "🇬🇺"},
    {"code": "cs-CZ", "name": "Čeština", "flag": "🇨🇿"},
    {"code": "cy-GB", "name": "Cymraeg", "flag": "🇬🇧"},
    {"code": "da-DK", "name": "Dansk", "flag": "🇩🇰"},
    {"code": "de-AT", "name": "Deutsch (AT)", "flag": "🇦🇹"},
    {"code": "de-CH", "name": "Deutsch (CH)", "flag": "🇨🇭"},
    {"code": "de-DE", "name": "Deutsch (DE)", "flag": "🇩🇪"},
    {"code": "el-CY", "name": "Ελληνικά", "flag": "🇨🇾"},
    {"code": "el-GR", "name": "Ελληνικά", "flag": "🇬🇷"},
    {"code": "en-AG", "name": "English (AG)", "flag": "🇦🇬"},
    {"code": "en-AU", "name": "English (AU)", "flag": "🇦🇺"},
    {"code": "en-BB", "name": "English (BB)", "flag": "🇧🇧"},
    {"code": "en-BZ", "name": "English (BZ)", "flag": "🇧🇿"},
    {"code": "en-CA", "name": "English (CA)", "flag": "🇨🇦"},
    {"code": "en-CM", "name": "English (CM)", "flag": "🇨🇲"},
    {"code": "en-GB", "name": "English (UK)", "flag": "🇬🇧"},
    {"code": "en-GG", "name": "English (GG)", "flag": "🇬🇬"},
    {"code": "en-GH", "name": "English (GH)", "flag": "🇬🇭"},
    {"code": "en-GI", "name": "English (GI)", "flag": "🇬🇮"},
    {"code": "en-GY", "name": "English (GY)", "flag": "🇬🇾"},
    {"code": "en-IE", "name": "English (IE)", "flag": "🇮🇪"},
    {"code": "en-JM", "name": "English (JM)", "flag": "🇯🇲"},
    {"code": "en-KE", "name": "English (KE)", "flag": "🇰🇪"},
    {"code": "en-LC", "name": "English (LC)", "flag": "🇱🇨"},
    {"code": "en-MW", "name": "English (MW)", "flag": "🇲🇼"},
    {"code": "en-NZ", "name": "English (NZ)", "flag": "🇳🇿"},
    {"code": "en-PG", "name": "English (PG)", "flag": "🇵🇬"},
    {"code": "en-TC", "name": "English (TC)", "flag": "🇹🇨"},
    {"code": "en-US", "name": "English (US)", "flag": "🇺🇸"},
    {"code": "en-ZM", "name": "English (ZM)", "flag": "🇿🇲"},
    {"code": "en-ZW", "name": "English (ZW)", "flag": "🇿🇼"},
    {"code": "eo-EO", "name": "Esperanto", "flag": "🌍"},
    {"code": "es-AR", "name": "Español (AR)", "flag": "🇦🇷"},
    {"code": "es-CL", "name": "Español (CL)", "flag": "🇨🇱"},
    {"code": "es-DO", "name": "Español (DO)", "flag": "🇩🇴"},
    {"code": "es-EC", "name": "Español (EC)", "flag": "🇪🇨"},
    {"code": "es-ES", "name": "Español (ES)", "flag": "🇪🇸"},
    {"code": "es-GQ", "name": "Español (GQ)", "flag": "🇬🇶"},
    {"code": "es-GT", "name": "Español (GT)", "flag": "🇬🇹"},
    {"code": "es-HN", "name": "Español (HN)", "flag": "🇭🇳"},
    {"code": "es-MX", "name": "Español (MX)", "flag": "🇲🇽"},
    {"code": "es-NI", "name": "Español (NI)", "flag": "🇳🇮"},
    {"code": "es-PA", "name": "Español (PA)", "flag": "🇵🇦"},
    {"code": "es-PE", "name": "Español (PE)", "flag": "🇵🇪"},
    {"code": "es-PY", "name": "Español (PY)", "flag": "🇵🇾"},
    {"code": "es-SV", "name": "Español (SV)", "flag": "🇸🇻"},
    {"code": "es-UY", "name": "Español (UY)", "flag": "🇺🇾"},
    {"code": "et-EE", "name": "Eesti", "flag": "🇪🇪"},
    {"code": "eu-ES", "name": "Euskara", "flag": "🇪🇸"},
    {"code": "fa-IR", "name": "فارسی", "flag": "🇮🇷"},
    {"code": "fi-FI", "name": "Suomi", "flag": "🇫🇮"},
    {"code": "fr-BF", "name": "Français (BF)", "flag": "🇧🇫"},
    {"code": "fr-CA", "name": "Français (CA)", "flag": "🇨🇦"},
    {"code": "fr-CD", "name": "Français (CD)", "flag": "🇨🇩"},
    {"code": "fr-CI", "name": "Français (CI)", "flag": "🇨🇮"},
    {"code": "fr-FR", "name": "Français (FR)", "flag": "🇫🇷"},
    {"code": "fr-GF", "name": "Français (GF)", "flag": "🇬🇫"},
    {"code": "fr-GP", "name": "Français (GP)", "flag": "🇬🇵"},
    {"code": "fr-MC", "name": "Français (MC)", "flag": "🇲🇨"},
    {"code": "fr-ML", "name": "Français (ML)", "flag": "🇲🇱"},
    {"code": "fr-MU", "name": "Français (MU)", "flag": "🇲🇺"},
    {"code": "fr-PF", "name": "Français (PF)", "flag": "🇵🇫"},
    {"code": "ga-IE", "name": "Gaeilge", "flag": "🇮🇪"},
    {"code": "gd-GB", "name": "Gàidhlig", "flag": "🇬🇧"},
    {"code": "gl-ES", "name": "Galego", "flag": "🇪🇸"},
    {"code": "he-IL", "name": "עברית", "flag": "🇮🇱"},
    {"code": "hi-IN", "name": "हिन्दी", "flag": "🇮🇳"},
    {"code": "hr-HR", "name": "Hrvatski", "flag": "🇭🇷"},
    {"code": "hu-HU", "name": "Magyar", "flag": "🇭🇺"},
    {"code": "id-ID", "name": "Bahasa Indonesia", "flag": "🇮🇩"},
    {"code": "it-IT", "name": "Italiano (IT)", "flag": "🇮🇹"},
    {"code": "it-VA", "name": "Italiano (VA)", "flag": "🇻🇦"},
    {"code": "ja-JP", "name": "日本語", "flag": "🇯🇵"},
    {"code": "ka-GE", "name": "ქართული", "flag": "🇬🇪"},
    {"code": "kk-KZ", "name": "Қазақша", "flag": "🇰🇿"},
    {"code": "kn-IN", "name": "ಕನ್ನಡ", "flag": "🇮🇳"},
    {"code": "ko-KR", "name": "한국어", "flag": "🇰🇷"},
    {"code": "ku-TR", "name": "Kurdî", "flag": "🇹🇷"},
    {"code": "ky-KG", "name": "Кыргызча", "flag": "🇰🇬"},
    {"code": "lt-LT", "name": "Lietuvių", "flag": "🇱🇹"},
    {"code": "lv-LV", "name": "Latviešu", "flag": "🇱🇻"},
    {"code": "ml-IN", "name": "മലയാളം", "flag": "🇮🇳"},
    {"code": "mr-IN", "name": "मराठी", "flag": "🇮🇳"},
    {"code": "ms-MY", "name": "Bahasa Melayu (MY)", "flag": "🇲🇾"},
    {"code": "ms-SG", "name": "Bahasa Melayu (SG)", "flag": "🇸🇬"},
    {"code": "nb-NO", "name": "Norsk Bokmål", "flag": "🇳🇴"},
    {"code": "nl-BE", "name": "Nederlands (BE)", "flag": "🇧🇪"},
    {"code": "nl-NL", "name": "Nederlands (NL)", "flag": "🇳🇱"},
    {"code": "no-NO", "name": "Norsk", "flag": "🇳🇴"},
    {"code": "pa-IN", "name": "ਪੰਜਾਬੀ", "flag": "🇮🇳"},
    {"code": "pl-PL", "name": "Polski", "flag": "🇵🇱"},
    {"code": "pt-AO", "name": "Português (AO)", "flag": "🇦🇴"},
    {"code": "pt-BR", "name": "Português (BR)", "flag": "🇧🇷"},
    {"code": "pt-MZ", "name": "Português (MZ)", "flag": "🇲🇿"},
    {"code": "pt-PT", "name": "Português (PT)", "flag": "🇵🇹"},
    {"code": "ro-MD", "name": "Română (MD)", "flag": "🇲🇩"},
    {"code": "ro-RO", "name": "Română (RO)", "flag": "🇷🇴"},
    {"code": "ru-RU", "name": "Русский", "flag": "🇷🇺"},
    {"code": "si-LK", "name": "සිංහල", "flag": "🇱🇰"},
    {"code": "sk-SK", "name": "Slovenčina", "flag": "🇸🇰"},
    {"code": "sl-SI", "name": "Slovenščina", "flag": "🇸🇮"},
    {"code": "so-SO", "name": "Soomaali", "flag": "🇸🇴"},
    {"code": "sq-AL", "name": "Shqip (AL)", "flag": "🇦🇱"},
    {"code": "sq-XK", "name": "Shqip (XK)", "flag": "🇽🇰"},
    {"code": "sr-ME", "name": "Српски (ME)", "flag": "🇲🇪"},
    {"code": "sr-RS", "name": "Српски (RS)", "flag": "🇷🇸"},
    {"code": "sv-SE", "name": "Svenska", "flag": "🇸🇪"},
    {"code": "sw-TZ", "name": "Kiswahili", "flag": "🇹🇿"},
    {"code": "ta-IN", "name": "தமிழ்", "flag": "🇮🇳"},
    {"code": "te-IN", "name": "తెలుగు", "flag": "🇮🇳"},
    {"code": "th-TH", "name": "ไทย", "flag": "🇹🇭"},
    {"code": "tl-PH", "name": "Tagalog", "flag": "🇵🇭"},
    {"code": "tr-TR", "name": "Türkçe", "flag": "🇹🇷"},
    {"code": "uk-UA", "name": "Українська", "flag": "🇺🇦"},
    {"code": "ur-PK", "name": "اردو", "flag": "🇵🇰"},
    {"code": "uz-UZ", "name": "Oʻzbekcha", "flag": "🇺🇿"},
    {"code": "vi-VN", "name": "Tiếng Việt", "flag": "🇻🇳"},
    {"code": "zh-CN", "name": "中文 (CN)", "flag": "🇨🇳"},
    {"code": "zh-HK", "name": "中文 (HK)", "flag": "🇭🇰"},
    {"code": "zh-SG", "name": "中文 (SG)", "flag": "🇸🇬"},
    {"code": "zh-TW", "name": "中文 (TW)", "flag": "🇹🇼"},
    {"code": "zu-ZA", "name": "isiZulu", "flag": "🇿🇦"},
]

def get_language_display(code: str) -> str:
    """Get display string for a language code."""
    for lang in SUPPORTED_LANGUAGES:
        if lang['code'] == code:
            return f"{lang['name']}"
    return code

def get_language_code(display: str) -> str:
    """Extract language code from display string."""
    for lang in SUPPORTED_LANGUAGES:
        display_str = f"{lang['name']}"
        if display_str == display:
            return lang['code']
    return "en-US"  # Default
